<?php


namespace SilverStripe\Cow\Utility;


use SilverStripe\Cow\Model\Modules\Module;
use SilverStripe\Cow\Steps\Step;
use Symfony\Component\Console\Output\OutputInterface;

class Translations
{

    /**
     * Generate javascript for all modules
     *
     * @param Step $step
     * @param OutputInterface $output
     * @param Module[] $modules
     */
    public static function generateJavascript(Step $step, OutputInterface $output, $modules)
    {
        $step->log($output, "Generating javascript locale files");
        // Check which paths in each module require processing
        $count = 0;
        foreach ($modules as $module) {
            $base = $module->getMainDirectory();
            $jsPath = $module->getJSLangDirectories();
            foreach ((array)$jsPath as $path) {
                $count += static::generateJavascriptInDirectory($step, $output, $base, $path);
            }
        }
        $step->log($output, "Finished generating {$count} files");
    }


    /**
     * Process all javascript in a given path
     *
     * @param Step $step
     * @param OutputInterface $output
     * @param string $base Base directory of the module
     * @param string $path Path to the location of JS files
     * @return int Number of files generated
     */
    protected static function generateJavascriptInDirectory(Step $step, OutputInterface $output, $base, $path)
    {
        // Iterate through each source file
        $count = 0;
        $template = <<<TMPL
// This file was generated by silverstripe/cow from %FILE%.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('%LOCALE%', %TRANSLATIONS%);
}
TMPL;
        // Update each source file
        foreach (glob("{$path}/src/*.js") as $sourceFile) {
            $count++;
            // Get contents and location
            $sourceArray = Config::loadFromFile($sourceFile);
            $sourceContents = Config::encodeContents($sourceArray);
            $locale = preg_replace('/\.js$/', '', basename($sourceFile));
            $targetFile = dirname(dirname($sourceFile)) . '/' . $locale . '.js';

            if (OutputInterface::VERBOSITY_VERY_VERBOSE <= $output->getVerbosity()) {
                $step->log($output, "Generating file {$targetFile}", "info");
            }

            file_put_contents(
                $targetFile,
                str_replace(
                    array(
                        '%TRANSLATIONS%',
                        '%FILE%',
                        '%LOCALE%'
                    ),
                    array(
                        $sourceContents,
                        substr($sourceFile, strlen($base) + 1), // Trim off base dir
                        $locale
                    ),
                    $template
                )
            );
        }
        return $count;
    }
}